server:
  port: 8082

spring:
  application:
    name: processing-service
  config:
    import: classpath:pfm-defaults.yml
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    streams:
      application-id: processing-service
      properties:
        processing.guarantee: exactly_once_v2

processing:
  topic: ${pfm.topic}

management:
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState, kafkaStreams
        liveness:
          include: livenessState, kafkaStreams
