server:
  port: 8082

spring:
  application:
    name: processing-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    streams:
      application-id: processing-service
      properties:
        processing.guarantee: exactly_once_v2

processing:
  topic: future-transactions

management:
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState, kafkaStreams
        liveness:
          include: livenessState, kafkaStreams
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
